# Generated by Django 2.2.6 on 2019-10-08 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loginDetails',
            fields=[
                ('SAP_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100, unique=True)),
                ('Two_Step', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='userAcc',
            fields=[
                ('SAP_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='expmgr.loginDetails')),
                ('Balance', models.IntegerField()),
                ('Savings_Goal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('SAP_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='expmgr.loginDetails')),
                ('Full_Name', models.CharField(max_length=50, unique=True)),
                ('Phone_No', models.IntegerField(unique=True)),
                ('Email_ID', models.EmailField(max_length=254, unique=True)),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='incomeStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Income_Id', models.UUIDField(help_text='Auto Generate UID for each user', unique=True)),
                ('Income_Stream', models.CharField(max_length=50)),
                ('Amount', models.IntegerField()),
                ('Income_Date', models.DateTimeField(auto_now_add=True)),
                ('Notes', models.TextField(null=True)),
                ('SAP_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expmgr.loginDetails')),
            ],
            options={
                'unique_together': {('SAP_ID', 'Income_Id')},
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expense_Id', models.UUIDField(help_text='Auto Generate UID for each user', unique=True)),
                ('Expense_Name', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Expense_Date', models.DateTimeField(auto_now_add=True)),
                ('Category', models.CharField(choices=[('Food', 'Food'), ('Shopping', 'Shopping'), ('Travel', 'Travel'), ('Stationery', 'Stationery'), ('Phone Bill', 'Phone Bill'), ('Personal', 'Personal'), ('Leisure', 'Leisure'), ('Misc', 'Miscellaneous')], max_length=10)),
                ('Payment_Mode', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('E-Wallet', 'E-Wallet')], max_length=8)),
                ('Bill_Img', models.FileField(help_text='Insert bill image here', null=True, upload_to='')),
                ('Notes', models.TextField(null=True)),
                ('SAP_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expmgr.loginDetails')),
            ],
            options={
                'unique_together': {('SAP_ID', 'Expense_Id')},
            },
        ),
    ]
