# Generated by Django 2.2.6 on 2019-10-08 23:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('expmgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='Expense_Id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Auto Generate UID for each user', unique=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='Notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incomestream',
            name='Income_Id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Auto Generate UID for each user', unique=True),
        ),
        migrations.AlterField(
            model_name='incomestream',
            name='Notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
