# Generated by Django 2.2.6 on 2019-10-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expmgr', '0002_auto_20191009_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='Bill_Img',
            field=models.FileField(blank=True, help_text='Insert bill image here', null=True, upload_to=''),
        ),
    ]
