# Generated by Django 2.2.6 on 2019-10-08 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expmgr', '0003_auto_20191009_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='Expense_Name',
        ),
    ]
