# Generated by Django 2.2.4 on 2019-08-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='spacexLaunchData',
            fields=[
                ('mission_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('flight_No', models.IntegerField(max_length=3)),
                ('launch_Date', models.CharField(max_length=20)),
                ('rocket_Manufacturer', models.CharField(max_length=25)),
            ],
        ),
    ]
